# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Data Scientist"
description: > # this means to ignore newlines until "email:"
   Data Scientist가 되고 싶은 성장하는 데린이

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/home.png"
blog_logo: "/assets/images/bmk.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Bom'
author: 'Bom'
author_image: "/assets/images/bmk.png"

paginate:	5

url: "http://bominkm.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	http://bominkm.github.io/project/
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown
kramdown:
 input: GFM

# disqus
disqus_shortname: Bomin
